### ISSUE TITLE
Unmet dependencies exception when enabling message_example module

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#114]
Using 9c840ded: Rename messageType to messageTemplate

```
drush en message_example -y
The following extensions will be enabled: message_example, token
Do you really want to continue? (y/n): y
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects (field.field.message.example_create_comment.field_comment_reference,  [error]
field.field.message.example_create_comment.field_node_reference, field.field.message.example_create_comment.field_published,
field.field.message.example_create_node.field_node_reference, field.field.message.example_create_node.field_published) provided by message_example have unmet
dependencies' in /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:84
Stack trace:
#0 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Config/ConfigInstaller.php(460): Drupal\Core\Config\UnmetDependenciesException::create('message_example', Array)
#1 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132):
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'message_example')
#2 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'message_example')
#3 /Applications/MAMP/htdocs/drupal-8/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, true)
#4 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/core/drupal/environment.inc(131): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
true)
#5 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/core/drupal/environment.inc(198): drush_module_install(Array)
#6 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1167): drush_module_enable(Array)
#7 [internal function]: drush_pm_enable('message_example')
#8 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(366): call_user_func_array('drush_pm_enable', Array)
#9 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#10 [internal function]: drush_command('message_example')
#11 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#12 /Users/paulmccrodden/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#13 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#14 /Users/paulmccrodden/.composer/vendor/drush/drush/drush.php(12): drush_main()
#15 {main}
```

**Comment by amitaibu** [comment]
Oh, we didn't take proper care of the example module. Care to create a PR?

**Comment by mccrodp** [comment]
I just noticed: https://github.com/Gizra/message/pull/113
