### ISSUE TITLE
Not possible to uninstall module due to incorrect use of config object

### ISSUE THREAD

**Issue by mccrodp** [Gizra/message#34]
```
$ drush pm-uninstall message
The following extensions will be uninstalled: message
Do you really want to continue? (y/n): y
exception 'Drupal\Core\Config\ImmutableConfigException' with message 'Can not delete immutable configuration message.message. Use                    [error]
\Drupal\Core\Config\ConfigFactoryInterface::getEditable() to retrieve a mutable configuration object' in
/Applications/MAMP/htdocs/d8.message-ui.upgrade/core/lib/Drupal/Core/Config/ImmutableConfig.php:56
Stack trace:
#0 /Applications/MAMP/htdocs/d8.message-ui.upgrade/modules/message/message.install(21):
Drupal\Core\Config\ImmutableConfig->delete('delete_cron_lim...')
#1 [internal function]: message_uninstall()
#2 /Applications/MAMP/htdocs/d8.message-ui.upgrade/core/lib/Drupal/Core/Extension/ModuleHandler.php(383): call_user_func_array('message_uninsta...',
Array)
#3 /Applications/MAMP/htdocs/d8.message-ui.upgrade/core/lib/Drupal/Core/Extension/ModuleInstaller.php(356):
Drupal\Core\Extension\ModuleHandler->invoke('message', 'uninstall')
#4 /Applications/MAMP/htdocs/d8.message-ui.upgrade/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(95):
Drupal\Core\Extension\ModuleInstaller->uninstall(Array, true)
#5 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/core/drupal/environment.inc(225):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->uninstall(Array)
#6 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/core/drupal/pm_8.inc(80): drush_module_uninstall(Array)
#7 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1190): _drush_pm_uninstall(Array)
#8 [internal function]: drush_pm_uninstall('message')
#9 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(359): call_user_func_array('drush_pm_uninst...', Array)
#10 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
#11 [internal function]: drush_command('message')
#12 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(178): call_user_func_array('drush_command', Array)
#13 /Users/paulmccrodden/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#14 /Users/paulmccrodden/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 /Users/paulmccrodden/.composer/vendor/drush/drush/drush.php(11): drush_main()
#16 {main}
```

**Comment by mccrodp** [comment]
Fixed in PR: https://github.com/Gizra/message/pull/45
